# Generated by Django 5.1 on 2024-08-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Male',
        ),
        migrations.AlterField(
            model_name='female',
            name='name_female',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
