# Generated by Django 5.1 on 2024-08-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_phone_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouchahed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidname', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
