# Generated by Django 5.1 on 2024-08-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_mouchahed_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouchahed',
            name='vid',
            field=models.ManyToManyField(null=True, to='pages.video'),
        ),
    ]
