# Generated by Django 5.1 on 2024-08-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-price'], 'verbose_name': 'Hajat tetchrab'},
        ),
        migrations.AddField(
            model_name='product',
            name='ca',
            field=models.CharField(blank=True, choices=[('Ma3dani', 'Ma3dani'), ('Soda', 'Soda')], max_length=50, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, default='ousef mantoujek', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='your name', max_length=50, verbose_name='esmk'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
