# Generated by Django 5.1 on 2024-08-14 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_product_ca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('now', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='ca',
            field=models.CharField(blank=True, choices=[('Ma3dani', 'Ma3dani'), ('Soda', 'Soda')], max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, default='Ousef mantoujek', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Youre name', max_length=50, verbose_name='esmk'),
        ),
    ]
