# Generated by Django 5.1 on 2024-08-14 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_time_alter_product_ca_alter_product_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='date',
        ),
        migrations.RemoveField(
            model_name='time',
            name='time',
        ),
    ]
