# Generated by Django 5.1 on 2024-08-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_time_date_remove_time_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Hajat tetchrab'},
        ),
        migrations.AlterField(
            model_name='product',
            name='ca',
            field=models.CharField(blank=True, choices=[('Ma3dani', 'Ma3dani'), ('Soda', 'Soda'), ('Chrab', 'Chrab')], max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Lesm', max_length=50),
        ),
    ]
